POST http://localhost:8000/api/users
Content-Type: application/json

###
GET http://localhost:8000/api/users

###

DELETE http://localhost:8000/api/users/:id

###

PUT http://localhost:8000/api/users/:id
Content-Type: application/json
